# Generated by Django 4.2 on 2025-01-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_url", models.URLField()),
                ("key", models.CharField(max_length=50, unique=True)),
                ("secret_key", models.CharField(max_length=50, unique=True)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
