# Generated by Django 4.2 on 2025-01-13 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("urlshortener", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="url",
            old_name="active",
            new_name="is_active",
        ),
    ]
